package com.pojo;
// Generated Sep 26, 2017 4:12:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TcStatus generated by hbm2java
 */
public class TcStatus  implements java.io.Serializable {


     private Integer id;
     private TcDesc tcDesc;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }
     private Date date;
     private String status;
     private String time;
     private String module;

    public TcStatus() {
    }

    public TcStatus(TcDesc tcDesc, Date date, String status, String module) {
       this.tcDesc = tcDesc;
       this.date = date;
       this.status = status;
       this.module = module;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TcDesc getTcDesc() {
        return this.tcDesc;
    }
    
    public void setTcDesc(TcDesc tcDesc) {
        this.tcDesc = tcDesc;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }




}


